package exception_ex;

public class Ex01 {

	public static void main(String[] args) {

		// 에외처리 : 예상치 못한 상황에 대한 처리를 하는 것
		// try - catch - finally

		// NPE
		try {
			String str = null;
			System.out.println(str.isEmpty());

			int[] arr = { 1, 2, 3 };
			for (int i = 0; i <= arr.length; i++) {
				System.out.println(arr[i]);
			}
		} catch (NullPointerException e) {
			System.err.println("NPF가 발생했다");
		} catch (ArrayIndexOutOfBoundsException e ) {
			System.err.println("배열 참조 오류가 발생했다");
		}

	}

}
